language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar self-update
  - php composer.phar install --prefer-source --dev

script:
  - ./vendor/bin/phpunit -c ./phpunit.xml --coverage-clover ./build/logs/clover.xml --exclude-group Performance
  - ./vendor/bin/phpunit --group=Functional
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/

branches:
  only:
    - master

after_script:
  - php vendor/bin/coveralls -v
